services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    networks:
      - web
networks:
  web:
    external: true
    name: trainers-manager_training_net